# Generated by Django 3.2.1 on 2021-05-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
