# Generated by Django 3.2.1 on 2021-05-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='sex',
            new_name='card_type',
        ),
    ]
