# Generated by Django 3.2.1 on 2021-05-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0002_rename_sex_payment_card_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='card_type',
            new_name='pay_type',
        ),
    ]
