# Generated by Django 3.2.1 on 2021-05-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0004_auto_20210509_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='store',
        ),
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=8),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_type',
            field=models.CharField(choices=[('CARD', 'CARD'), ('MANUAL', 'MANUAL')], default='CARD', max_length=7),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='status',
            field=models.CharField(blank=True, choices=[('LOCKED', 'LOCKED'), ('UNLOCKED', 'UNLOCKED')], max_length=9, null=True),
        ),
    ]
