# Generated by Django 3.2.1 on 2021-05-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0005_auto_20210509_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=8),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_type',
            field=models.CharField(choices=[('CARD', 'Card'), ('MANUAL', 'Manual')], default='CARD', max_length=7),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='status',
            field=models.CharField(blank=True, choices=[('LOCKED', 'Locked'), ('UNLOCKED', 'Unlocked')], max_length=9, null=True),
        ),
    ]
