# Generated by Django 3.2.1 on 2021-05-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0006_auto_20210511_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='salutation',
            field=models.CharField(choices=[('MR', 'Mr'), ('MS', 'Ms')], max_length=7),
        ),
    ]
