# Generated by Django 3.2.1 on 2021-05-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0007_alter_profile_salutation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=8),
        ),
    ]
