# Generated by Django 3.2.1 on 2021-05-18 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0009_alter_account_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='churchaio.profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='churchaio.profile'),
        ),
    ]
