# Generated by Django 3.2.1 on 2021-05-31 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0011_auto_20210518_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_count',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('IMMATURE', 'Immature'), ('MATURE', 'Mature'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='IMMATURE', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='churchaio.profile'),
        ),
    ]
