# Generated by Django 3.2.1 on 2021-06-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0012_auto_20210601_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
