# Generated by Django 3.2.1 on 2021-07-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0016_auto_20210627_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='photo',
        ),
        migrations.AddField(
            model_name='account',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
    ]
