# Generated by Django 3.2.1 on 2021-08-04 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0019_auto_20210703_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='ip_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='port',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='proxy_list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='churchaio.proxylist'),
        ),
    ]
