# Generated by Django 3.2.1 on 2021-08-04 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0020_auto_20210804_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='proxy_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchaio.proxylist'),
        ),
    ]
