# Generated by Django 3.2.1 on 2021-08-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0021_alter_proxy_proxy_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
