# Generated by Django 3.2.1 on 2021-08-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0022_alter_proxy_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='webhook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='sku_link',
            field=models.URLField(),
        ),
    ]
