# Generated by Django 3.2.1 on 2021-08-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0023_auto_20210807_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='auto_solve',
            field=models.URLField(blank=True, null=True),
        ),
    ]
