# Generated by Django 3.2.1 on 2021-10-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0025_alter_account_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='zip_code',
        ),
    ]
