# Generated by Django 3.2.1 on 2021-10-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0025_alter_account_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='celery_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
