# Generated by Django 3.2.1 on 2021-11-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0026_remove_address_zip_code'),
        ('churchaio', '0026_task_celery_id'),
    ]

    operations = [
    ]
