# Generated by Django 3.2.1 on 2021-11-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0027_merge_20211117_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='store_name',
            field=models.CharField(choices=[('FOOTLOCKER', 'Footlocker'), ('JD_SPORTS', 'JD_Sports'), ('HYPEDC', 'hypedc'), ('CULTURE_KINGS', 'Culture Kings')], default='JD_SPORTS', max_length=50),
        ),
    ]
