# Generated by Django 3.2.1 on 2021-11-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0028_alter_task_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('IMMATURE', 'Immature'), ('MATURE', 'Mature'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed'), ('NO_SKU', 'SKU not found'), ('NO_SHOE', 'Shoe size not found'), ('CART_FAIL', 'Add to cart failed'), ('CHECKOUT_FAIL', 'Checkout failed'), ('PAYMENT_FAIL', 'Payment failed')], default='IMMATURE', max_length=30),
        ),
    ]
