# Generated by Django 3.2.1 on 2021-11-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchaio', '0029_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(max_length=100),
        ),
    ]
