# Generated by Django 3.2.1 on 2021-05-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakerbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='address',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='proxy_list',
        ),
        migrations.AlterUniqueTogether(
            name='proxylist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='proxylist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='task',
            name='proxy_list',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Proxy',
        ),
        migrations.DeleteModel(
            name='ProxyList',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
